### ISSUE TITLE
Stretch goals

### ISSUE THREAD

**Issue by souryavarenya** [cmm-20/final-project#1]
1. At the end of the presentation, it was mentioned that more stretch goals would be expected from a larger team. Is there a definitive baseline to this like 3 people - 3 tasks or 3 people - 5 tasks? What baseline would be enough to ensure a full score if everything is done perfectly?

2. Are the 5 stretch goals an exhaustive list of accepted ones or can others be proposed too? If yes, what would the procedure + deadline be for that?

**Comment by moritzge** [comment]
Hi,

I answered these questions in today's (May 11) Q&A session. For all who couldn't join, here's the answer again:

1. It depends on the team size. If you are a single-member team, you are expected to implement the Basic Goals, which are IK and gait controller. In the end, you would thus have a robot that can walk around and you control it with a virtual controller (e.g. forward, left, right, sideways ...). Of course you are free to also implement stretch goals. If you are a two-member team, then you are expected to implement the Basic Goals and one or two stretch goals, depending on the complexity of the stretch goals. And if you are a three-member team, you are expected to implement the Basic Goals and 2-3 stretch goals, again depending on their complexity. 

2. 5 stretch goals are certainly on the upper limit of how many stretch goals are reasonable. Of course you can split stretch goals into two goals. Best way to find out is to write an email to us with your ideas for stretch goals. We will get back to you and let you know if your goals are too high or too low.

In contrast to the assignments where you had to fullfill very specific tasks, we intentionally set the goals of the project loose enough so you do what you like most and have fun with it! Having fun with this project is the best way to get a good grade.
