### ISSUE TITLE
Draw static objects in the simulation e.g. spheres to represent targets

### ISSUE THREAD

**Issue by ghost** [cmm-20/final-project#11]
Hey guys!

I was wondering if somebody already implemented something like this?

Would be really helpful for debugging forward/inverse kinematics  :)

Best,
Leo

**Comment by nathanael-k** [comment]
Check the "guizmo" that is already implemented. You can enable it with a check box in the menue, itss coordinates are a field of the app.

**Comment by ghost** [comment]
Hey Nathanael

Thanks, but I don't really get that guizmo thingy, doesn't seem to be fixed w.r.t. inertial frame.

This is what  I was looking for :)
![image](https://user-images.githubusercontent.com/37075917/82804013-c9b0d300-9e81-11ea-993a-8b68194830cf.png)
