### ISSUE TITLE
Find foot position

### ISSUE THREAD

**Issue by ghost** [cmm-20/final-project#13]
Does anyone have a way of printing out the foot position in world or body frame? I am able to print out the position of the joints, but not the end effector. Thanks!

**Comment by gitmon** [comment]
Hi, you can find the list of each RobotRB's end effectors in RobotRB->rbProps.endEffectorPoints. This is an array of P3D points, giving each of the end effectors' positions on this rigid body (I believe in local coordinates). You can then convert this to world coordinates using the functions under RobotRB->state.

**Comment by ghost** [comment]
Hi, I've tried to print the endEffectorPoints, but the vector is empty and whenever I try to access the values by typing `std::cout << robot.root->state.getWorldCoordinates(robot.root->rbProps.endEffectorPoints[0]).x << std::endl;`
The application crashes when it reaches that line. Is there a better way to access `endEffectorPoints`?

**Comment by nathanael-k** [comment]
I don't have the code in front of me right now, but I guess the root does not have any endEffectorPoints,right? You need to go to the rbProbs of the actual rigid body, not of the root.
To get the rigid body, either check how they are indexed, or you can get them by name. The name you can see in the console when you hover over the rigid body.

**Comment by souryavarenya** [comment]
You can access them like this:

```
ee_rbs = robot.rbWithEndEffectors;
ee_rbs[i]->state.getWorldCoordinates(ee_rbs[i]->rbProps.endEffectorPoints[0]);
```

Explanation: Here, `ee_rbs` gets you a vector of rigid bodies containing end-effectors. Since each of this rigid bodies have only one end effector,  you get the local coordinates of it using `ee_rbs[i]->rbProps.endEffectorPoints[0]`. Once you have that, you can use `ee_rbs[i]->state.getWorldCoordinates()` to convert from local frame to world frame.

**Comment by ghost** [comment]
Ok, it seems to work now. Thanks a lot guys! Really appreciate the help!
