### ISSUE TITLE
Terrain Design

### ISSUE THREAD

**Issue by Skype-line** [cmm-20/final-project#14]
Hi,
Now we are trying to design our new terrains (e.g. Slope, stages). Could anyone show me any useful files or functions I can utilize? I think "guizmo" is more like the interactive way to create some static objects, whereas I want something like a static map with several cubes on the ground.
Thanks in advance :)

Best,
Kaiyue

**Comment by chaofiber** [comment]
I have the same question here. The default ground seems to be loaded from a preexisted file. can we have access to new grounds or how can we build a new terrain like stairs.

Similarly, we also need to add something like cylinders as a collision obstacle, could anyone give a hint where might be the code is?

Thanks,

**Comment by nathanael-k** [comment]
Sorry, but I have not looked too much into it. Basically, there are two things that happen: the actual physical ground which gets ultimately loaded into ODE for the simulation (i think it's just defined as a plane or something). And then the ground that you actually see, that is drawn to the screen. As far as I know these are totally separate things, and you would have to look into getting some new geometry into ODE to collide with. I am sure it is possible, but might need a bit of understanding of the simulation engine.
For my project, terrain is ultimately out of scope, so I unfortunately can't tell you much more.
