### ISSUE TITLE
Resetting the robot from within the app

### ISSUE THREAD

**Issue by souryavarenya** [cmm-20/final-project#16]
Hey guys, we are trying to use the same window for multiple tasks by just switching to another checkbox. Are there any readily available functions that can help reset the robot to its default flat floating state? We've tried a few options to reset it and haven't gotten anything to work properly yet.

Any pointers on this would be great. Thanks!

**Comment by gitmon** [comment]
You could have the following code which runs inside a button:

`for (auto &joint : robot.jointList) {
joint->controlMode = POSITION_MODE;
joint->desiredControlSignal = 0.0;
}
robot.setRootState(myPosition, myOrientation);`

Does that work?

**Comment by souryavarenya** [comment]
@gitmon Thanks for this comment - your help is greatly appreciated. I somehow missed this but I've tried this and it did not give me what I wanted. We have chosen another way to go about our problem.
