### ISSUE TITLE
error at build - Fetchcontent

### ISSUE THREAD

**Issue by rakrishn** [cmm-20/final-project#2]
Hello guys,
When I am trying to build the project with cmake, I get the error that the Fetchcontent file is not found.
How can I resolve this error?
![Screenshot from 2020-05-12 09-54-54](https://user-images.githubusercontent.com/56290014/81656746-93159a00-9437-11ea-8d70-4bb2365a91ba.png)

**Comment by souryavarenya** [comment]
Can you check your CMake version? `cmake --version`

3.11 is minimum for this macro.

**Comment by rakrishn** [comment]
I had a old version of cmake. Now after updating the version, it works fine.
Thank you.
