### ISSUE TITLE
Issue Building

### ISSUE THREAD

**Issue by ebonfalke** [cmm-20/final-project#5]
I get an error building the project on Windows10. (Past projects worked fine)
I get the following error:
``
CMake Error at ------/CMake/share/cmake-3.17/Modules/FetchContent.cmake:912 (message):
  Build step for tinyobjloader failed: 1
Call Stack (most recent call first):
  -----------/CMake/share/cmake-3.17/Modules/FetchContent.cmake:1003 (__FetchContent_directPopulate)
  ext/CMakeLists.txt:101 (FetchContent_Populate)

Configuring incomplete, errors occurred!
``
And in the Error log file:

``
cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_c111a.dir\Debug\\" /Fd"cmTC_c111a.dir\Debug\vc141.pdb" /Gd /TC /errorReport:queue "------\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c"

  CheckIncludeFile.c

  

-------\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "pthread.h": No such file or directory [---------------\build\CMakeFiles\CMakeTmp\cmTC_c111a.vcxproj]

``
Does anybody have an idea how to solve this error?

**Comment by moritzge** [comment]
Do you still have trouble building the code?
If so, what command did you run that produces the above outpt? `cmake ..` ?

**Comment by ebonfalke** [comment]
I tried it with cmake-gui  on Windows which worked fine until now but I couldn't figure out this error... 
In the end I switched to a Linux VM. There everything works fine. Since nobody else has the same issue I will close it.
