### ISSUE TITLE
Is feedback required in the Gait Controller?

### ISSUE THREAD

**Issue by nathanael-k** [cmm-20/final-project#7]
Right now I have a very simple implementation for the gait. Basically just a sequence of control inputs (calculated based on commands / target) that get sent to the motors. Since the tripod gait for a hexapod is very stable, this works well enough.

Is this sufficient? Or are we expected to implement more sophisticated control with feedback, for example checking if the legs touch the ground, or improving the gait to make it smoother / faster using some optimization technique?

**Comment by moritzge** [comment]
You do not need to make a closed loop controller. The goal is to make a controller that computes control inputs from high-level commands. So exactly what you say you did!
