### ISSUE TITLE
Access and usage of joint angles

### ISSUE THREAD

**Issue by davidestaub** [cmm-20/final-project#8]
Dear all,
I have two questions about access and usage of joints angles:

Firstly, I am a bit confused about the 'defaultJointAngle' variable used in app.h in the function 'computeAndApplyControlInputs'. In RBJoint.h we set defaultJointAngle = 0 and as far as I'm aware the value isn't altered anywhere else, so how come in the default pose the hexapod is standing and not lying 'flat' on the ground. I would have expected this behaviour since all the joint angles are equal to defaultJointAngle which in turn is equal to zero.

Secondly, where can one access something like the current angle of a joint? Maybe I'm wrong but the way I interpreted things 'desiredControlSignal' looks more like a "target angle" than a "current angle".
Thanks for any tipp in advance :) !

**Comment by nathanael-k** [comment]
Hey Davide,

if you load a robot, you provide a .rbs file. The hexapod is in `/robots/simple/hex.rb`. It's a pretty simple file format. In there, the default angles are stored. In the constructor of the robot, you can see that the actual loading is handed off to an `RBLoader` (look at the function `RBLoader::loadFromFile(const char*)`), that in turn populates the robot (create joints, set default angles and so on). But as long as you don't want to change anything there, it does not really matter.

Here you see all the methods and variables the class `RBJoint` offers: 
![image](https://user-images.githubusercontent.com/6664280/82122065-883d6b00-9791-11ea-91a2-d53185e68884.png)

The method you need is `getCurrentJointAngle()`. You will most probably also need `getWorldPosition()` and `rotationAxis` sooner or later.

Do you have an IDE with debugger and code completion? I think it can help a lot in such a project.

**Comment by chaofiber** [comment]
> Dear all,
> I have two questions about access and usage of joints angles:
> 
> Firstly, I am a bit confused about the 'defaultJointAngle' variable used in app.h in the function 'computeAndApplyControlInputs'. In RBJoint.h we set defaultJointAngle = 0 and as far as I'm aware the value isn't altered anywhere else, so how come in the default pose the hexapod is standing and not lying 'flat' on the ground. I would have expected this behaviour since all the joint angles are equal to defaultJointAngle which in turn is equal to zero.
> 
> Secondly, where can one access something like the current angle of a joint? Maybe I'm wrong but the way I interpreted things 'desiredControlSignal' looks more like a "target angle" than a "current angle".
> Thanks for any tipp in advance :) !

If you print out the joint.defaultJointAngle in the process function, you will find it is not zero anymore as when loading the configurations the default value is overrode.

**Comment by davidestaub** [comment]
Thank you both a lot for your answers ! :)
The first question is now cristal clear! 
Regarding the second one; my question was formulated a bit unclear, what I meant is: How can one set/alter the current angle of a Joint. getCurrentJointAngle() Doesn't really help with this as it returns the current angle. However I'm unable to find any member variable or method that would let me set the angle of a specific joint to a specific value.
What I came up with so far is to just pass the desired angular value to the 'desiredControlSignal' variable, but maybe there is a better way...

Thanks again for your help!

**Comment by moritzge** [comment]
Checkout this part of the wiki: https://github.com/cmm-20/final-project/wiki/Getting-Started#change-joint-angles

You can change joint angles by changing the value `joint->desiredControlSignal`.
