### ISSUE TITLE
Cant find a computegravityterm function

### ISSUE THREAD

**Issue by steffeol** [cmm-20/final-project#9]
Dear All

Our group is trying to solve the IK problem with Operational Space Control solved as a Quadratic Program. To do this we have to compute the mass matrix, the Coriolis and Centrifugal forces term and the gravity term. We have found the helpful functions computemassmatrix() and computeCoriolisAndCentrifugalForcesTerm() in GeneralizedCoordinatesRobotRepresentation.h but can't find the computeGravityTerm() function.

I guess it is somewhere in the code, as the other functions are given as well. Does someone know where I can find them or do we have to compute it on our own?

Best regards,
Oliver

**Comment by moritzge** [comment]
Hi Oliver,

You have to compute it yourself. 
A small hint: Gravity acts on the center of mass of all rigid bodies. However, you want the gravity term in Generalized Coordinates. Take a look at the function `GeneralizedCoordinatesRobotRepresentation::computeMassMatrix`. Yout funtion `computeGravityTerm` will look very similar. 

Best,
Moritz
